name: geog_env

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - seaborn
  - matplotlib==3.*
  - geopandas
  - mapclassify
  - cartopy
  - descartes
  - ipywidgets
  - contextily
  - pip:
      - plotly
      - statsmodels
      - scikit-learn
      


